name: SDK

on:
    push:
        branches: [main, develop, 'fix/*']
    pull_request:
        branches: [main, develop]

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macOS-latest]
                node: [14.x, 16.x]

        steps:
            - uses: actions/checkout@v2

            - name: Derive appropriate SHAs for base and head for `nx affected` commands
              uses: nrwl/nx-set-shas@v2

            - run: |
                  echo "Nx base: ${{ env.NX_BASE }}"
                  echo "Git head: ${{ env.NX_HEAD }}"

            - name: Use Node.js ${{ matrix.node }}
              uses: actions/setup-node@v2
              with:
                  node: ${{ matrix.node }}
                  cache: yarn

            - name: Disable TCP/UDP Offloading
              shell: bash
              run: |
                  if [ "$RUNNER_OS" == "Linux" ]; then
                    sudo ethtool -K eth0 tx off rx off
                    exit 0
                  elif [ "$RUNNER_OS" == "macOS" ]; then
                    sudo sysctl -w net.link.generic.system.hwcksum_tx=0
                    sudo sysctl -w net.link.generic.system.hwcksum_rx=0
                    exit 0
                  else
                    echo "$RUNNER_OS not supported"
                    exit 0
                  fi

            - name: Install repo dependencies
              run: |
                  yarn install --network-timeout 1000000 --forzen-lockfile

            - name: Check for lint
              run: |
                  yarn run lint-check --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }}

            - name: Build the Dev Suite
              run: |
                  yarn run build --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }}

            - name: Unit test the Dev Suite
              run: |
                  yarn run test --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }}

            - name: Execute end-to-end tests
              run: |
                  yarn run e2e --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }}
